language: node_js
node_js: 14

sudo: false

addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4

notifications:
  email: true

cache:
  npm: true
  directories:
    - ~/.cache
    - node_modules

before_script:
  - export TZ=Europe/Zurich

script:
  - npm run test:ci
  - npm run build:prod
  - npm run cy:ci
